blog/blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/groups/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

blog/posts/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views
from . import api_views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.post_profile, name='post'),
    path('add_post/', views.add_post, name='add_post'),
    path('cbv/posts/', views.PostListView.as_view(), name='posts_list'),
    path('login/', views.login_user, name='login'),
    path('category/<int:category_id>/', cache_page(100)(views.PostCategoryLiew.as_view()), name='category_list'),
    path('api_posts/', api_views.PostList.as_view(), name='post_list'),
    path('api_posts/<int:pk>/', api_views.PostDetail.as_view()),
]

blog/groups/models.py
from django.db import models


# Create your models here.
class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)


class Group(models.Model):
    name = models.CharField(max_length=30)
    members = models.ManyToManyField(Person, through='Membership')  # Won't be shown


class Membership(models.Model):
    person_id = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='Membership')
    group_id = models.ForeignKey(Group, on_delete=models.CASCADE)
    date_joined = models.DateField(auto_now=True)
    invite_reason = models.CharField(max_length=100)

blog/posts/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from tags.models import TaggedItem


# Create your models here.
class Post(models.Model):
    DRAFT = 0
    PUBLISH = 1
    REJECTED = 2
    STATUS_CHOICES = (
        (DRAFT, 'Draft'),
        (PUBLISH, 'Publish'),
        (REJECTED, 'Rejected'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=DRAFT)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100, unique=True)
    content = models.TextField()
    keywords = models.TextField(max_length=500, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)
    tags = GenericRelation(TaggedItem)

    class Meta:
        ordering = ['-updated_on']

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    is_active = models.BooleanField()
    meta_keywords = models.TextField(max_length=500, blank=True)
    description = models.TextField()
    tags = GenericRelation(TaggedItem)

    def __str__(self):
        return self.name

blog/tags/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class TaggedItem(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    # def __str__(self):
    #     return self.id

blog/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'category']

    def clean_title(self):
        data = self.cleaned_data['title']
        if len(data) < 5:
            raise forms.ValidationError("Title name is way too short!")
        return data

    def clean_content(self):
        data = self.cleaned_data['content']
        if len(data) < 30:
            raise forms.ValidationError("Pls, write some more text content")
        return data


class PostFormBackup(forms.Form):
    title = forms.CharField(label='Title', max_length=20)
    content = forms.CharField(label='Content', max_length=300)

    def clean_title(self):
        data = self.cleaned_data['title']
        if len(data) < 5:
            raise forms.ValidationError("Title name is way too short!")
        return data

    def clean_content(self):
        data = self.cleaned_data['content']
        if len(data) < 30:
            raise forms.ValidationError("Pls, write some more text content")
        return data

blog/groups/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Person
from .models import Group
from .models import Membership
from django.http import JsonResponse


def index(request):
    params = request.GET.dict()
    group_name = ''
    if 'group_name' in params:
        group_name = params['group_name']
        out_string = 'Got one'
    else:
        out_string = str(params)
    if group_name != '':
        out_string = group_name

    groups = Group.objects.all()
    print(groups[1].name)

    print(out_string)
    print(group_name)
    persons = list(Person.objects.filter(Membership__group_id__name=group_name).values())

    return JsonResponse(persons, safe=False)

# Create your views here.

blog/posts/views.py
# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, reverse
from .models import Post
from django.views.generic import ListView
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.shortcuts import Http404
import time
from django.views.decorators.cache import cache_page
from django.utils.translation import gettext_lazy as _


from .forms import PostForm


class PostListView(ListView):
    model = Post
    template_name = 'posts/index.html'
    context_object_name = 'posts'


class PostCategoryLiew(ListView):
    model = Post
    template_name = 'posts/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        print(self.kwargs['category_id'])
        category_id = self.kwargs['category_id']
        time.sleep(5)
        return self.model.objects.filter(category__id=category_id)


@cache_page(timeout=3600)
def index(request):
    time.sleep(2)
    return render(request, 'posts/index.html', context={"posts": Post.objects.select_related('category').all()})
    # print(request.GET.dict()['group_name'])
    # return HttpResponse(str(request.GET.dict()))


def post_profile(request, post_id):
    cnt = request.session.get('cnt', 0)
    cnt += 1
    request.session['cnt'] = cnt
    print(post_id)
    post = Post.objects.filter(id=post_id).first()
    print(post)
    return render(request, 'posts/post_profile.html', context={"post": post, 'cnt': cnt})


def add_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = Post(title=form.cleaned_data['title'],
                        content=form.cleaned_data['content'],
                        category=form.cleaned_data['category']
                        )
            post.save()
            print('from here')
            return HttpResponseRedirect('/posts')
        else:
            # return redirect()
            return render(request, 'posts/add_post.html', {'form': form})

    elif request.method == 'GET':
        form = PostForm()

    return render(request, 'posts/add_post.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['login'], password=request.POST['pass'])

        error_string = _("something went wrong")
        print(error_string)
        if user is None:
            raise Http404(error_string)
        login(request, user)
        return redirect('/posts/')

    return render(request, 'posts/login.html')

blog/tags/views.py
from django.shortcuts import render

# Create your views here.

blog/posts/templates/posts/add_post.html
<form action="{% url 'posts:add_post' %}"
      method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

blog/posts/templates/posts/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Blog Template · Bootstrap</title>


    {{request.user.username}}

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<link href="{%static 'posts/blog.css'%}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <!--<link href="blog.css" rel="stylesheet">-->
  </head>
  <body>
    <div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="text-muted" href="#">Subscribe</a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="#">Large</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3" focusable="false" role="img"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
        </a>
        <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
      </div>
    </div>
  </header>

  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 text-muted" href="#">World</a>
      <a class="p-2 text-muted" href="#">U.S.</a>
      <a class="p-2 text-muted" href="#">Technology</a>
      <a class="p-2 text-muted" href="#">Design</a>
      <a class="p-2 text-muted" href="#">Culture</a>
      <a class="p-2 text-muted" href="#">Business</a>
      <a class="p-2 text-muted" href="#">Politics</a>
      <a class="p-2 text-muted" href="#">Opinion</a>
      <a class="p-2 text-muted" href="#">Science</a>
      <a class="p-2 text-muted" href="#">Health</a>
      <a class="p-2 text-muted" href="#">Style</a>
      <a class="p-2 text-muted" href="#">Travel</a>
    </nav>
  </div>

  <!--<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">-->
    <!--<div class="col-md-6 px-0">-->
      <!--<h1 class="display-4 font-italic">Title of a longer featured blog post</h1>-->
      <!--<p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>-->
      <!--<p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>-->
    <!--</div>-->
  <!--</div>-->

  <!--<div class="row mb-2">-->
    <!--<div class="col-md-6">-->
      <!--<div class="card flex-md-row mb-4 shadow-sm h-md-250">-->
        <!--<div class="card-body d-flex flex-column align-items-start">-->
          <!--<strong class="d-inline-block mb-2 text-primary">World</strong>-->
          <!--<h3 class="mb-0">-->
            <!--<a class="text-dark" href="#">Featured post</a>-->
          <!--</h3>-->
          <!--<div class="mb-1 text-muted">Nov 12</div>-->
          <!--<p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>-->
          <!--<a href="#">Continue reading</a>-->
        <!--</div>-->
        <!--<svg class="bd-placeholder-img card-img-right flex-auto d-none d-lg-block" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect fill="#55595c" width="100%" height="100%"/><text fill="#eceeef" dy=".3em" x="50%" y="50%">Thumbnail</text></svg>-->
      <!--</div>-->
    <!--</div>-->
    <!--<div class="col-md-6">-->
      <!--<div class="card flex-md-row mb-4 shadow-sm h-md-250">-->
        <!--<div class="card-body d-flex flex-column align-items-start">-->
          <!--<strong class="d-inline-block mb-2 text-success">Design</strong>-->
          <!--<h3 class="mb-0">-->
            <!--<a class="text-dark" href="#">Post title</a>-->
          <!--</h3>-->
          <!--<div class="mb-1 text-muted">Nov 11</div>-->
          <!--<p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>-->
          <!--<a href="#">Continue reading</a>-->
        <!--</div>-->
        <!--<svg class="bd-placeholder-img card-img-right flex-auto d-none d-lg-block" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect fill="#55595c" width="100%" height="100%"/><text fill="#eceeef" dy=".3em" x="50%" y="50%">Thumbnail</text></svg>-->
      <!--</div>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->

<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom">
        From the Firehose
      </h3>

      <!--<div class="blog-post">-->
        <!--<h2 class="blog-post-title">Sample blog post</h2>-->
        <!--<p class="blog-post-meta">January 1, 2014 by <a href="#">Mark</a></p>-->

        <!--<p>This blog post shows a few different types of content that’s supported and styled with Bootstrap. Basic typography, images, and code are all supported.</p>-->
        <!--<hr>-->
        <!--<p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>-->
        <!--<blockquote>-->
          <!--<p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>-->
        <!--</blockquote>-->
        <!--<p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>-->
        <!--<h2>Heading</h2>-->
        <!--<p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>-->
        <!--<h3>Sub-heading</h3>-->
        <!--<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>-->
        <!--<pre><code>Example code block</code></pre>-->
        <!--<p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>-->
        <!--<h3>Sub-heading</h3>-->
        <!--<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>-->
        <!--<ul>-->
          <!--<li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>-->
          <!--<li>Donec id elit non mi porta gravida at eget metus.</li>-->
          <!--<li>Nulla vitae elit libero, a pharetra augue.</li>-->
        <!--</ul>-->
        <!--<p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>-->
        <!--<ol>-->
          <!--<li>Vestibulum id ligula porta felis euismod semper.</li>-->
          <!--<li>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</li>-->
          <!--<li>Maecenas sed diam eget risus varius blandit sit amet non magna.</li>-->
        <!--</ol>-->
        <!--<p>Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis.</p>-->
      <!--</div>&lt;!&ndash; /.blog-post &ndash;&gt;-->

      <!--<div class="blog-post">-->
        <!--<h2 class="blog-post-title">Another blog post</h2>-->
        <!--<p class="blog-post-meta">December 23, 2013 by <a href="#">Jacob</a></p>-->

        <!--<p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>-->
        <!--<blockquote>-->
          <!--<p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>-->
        <!--</blockquote>-->
        <!--<p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>-->
        <!--<p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>-->
      <!--</div>&lt;!&ndash; /.blog-post &ndash;&gt;-->

      <!--<div class="blog-post">-->
        <!--<h2 class="blog-post-title">New feature</h2>-->
        <!--<p class="blog-post-meta">December 14, 2013 by <a href="#">Chris</a></p>-->

        <!--<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>-->
        <!--<ul>-->
          <!--<li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>-->
          <!--<li>Donec id elit non mi porta gravida at eget metus.</li>-->
          <!--<li>Nulla vitae elit libero, a pharetra augue.</li>-->
        <!--</ul>-->
        <!--<p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>-->
        <!--<p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>-->
      <!--</div>&lt;!&ndash; /.blog-post &ndash;&gt;-->

      {% block content %}
      {% endblock %}

      <nav class="blog-pagination">
        <a class="btn btn-outline-primary" href="#">Older</a>
        <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
      </nav>

    </div><!-- /.blog-main -->

  </div><!-- /.row -->

</main><!-- /.container -->

<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script></body>
</html>

blog/posts/templates/posts/index.html
{% extends "posts/base.html" %}

{% block content %}

  {% for post in posts %}
    <h1>
      Category: {{post.category}}
      <br>
      <a href="{% url 'posts:post' post.id %}" >
        {{post.title}}
      </a>
    </h1>
    <p> {{post.content}} </p>
  {% endfor %}

{% endblock %}

blog/posts/templates/posts/login.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% get_current_language as CUR_LANGUAGE %}
    {{ CUR_LANGUAGE }}
    {% get_available_languages as LANGS %}
    {{ LANGS }}

     <form action="" method="post">
        {% csrf_token %}
         {% trans "Loginio" %}
         <br>
         <label for="login"> login </label> <input name="login" id="login" type="text">
         <label for="pass"> pass  </label><input name="pass" id="pass" type="password">
         <p><input type="submit"></p>
     </form>
</head>
<body>

</body>
</html>

blog/posts/templates/posts/post_profile.html
{% extends "posts/base.html" %}

{% block content %}

    <h1> {{post.title}} </h1>
    <p> {{post.content}} </p>
    <p> Times viewed: {{cnt}}</p>

{% endblock %}